In [1]:
import pandas as pd
import numpy as np

In [2]:
X_train=pd.read_csv('Final_X_train.csv')

In [3]:
X_train

Id  SalePrice  LotShape  BldgType  OverallQual  YearBuilt  \
0        1  12.247694       1.0       0.0     0.666667   0.949275   
1        2  12.109011       1.0       0.0     0.555556   0.753623   
2        3  12.317167       0.0       0.0     0.666667   0.934783   
3        4  11.849398       0.0       0.0     0.666667   0.311594   
4        5  12.429216       0.0       0.0     0.777778   0.927536   
...    ...        ...       ...       ...          ...        ...   
1455  1456  12.072541       1.0       0.0     0.555556   0.920290   
1456  1457  12.254863       1.0       0.0     0.555556   0.768116   
1457  1458  12.493130       1.0       0.0     0.666667   0.500000   
1458  1459  11.864462       1.0       0.0     0.444444   0.565217   
1459  1460  11.901583       1.0       0.0     0.444444   0.673913   

      YearRemodAdd  ExterQual  BsmtQual  BsmtExposure  ...  GrLivArea  \
0         0.883333   0.666667       0.5          1.00  ...   0.577712   
1         0.433333   1.000000       0.5          0.25  ...   0.470245   
2         0.866667   0.666667       0.5          0.75  ...   0.593095   
3         0.333333   1.000000       1.0          1.00  ...   0.579157   
4         0.833333   0.666667       0.5          0.00  ...   0.666523   
...            ...        ...       ...           ...  ...        ...   
1455      0.833333   1.000000       0.5          1.00  ...   0.564433   
1456      0.633333   1.000000       0.5          1.00  ...   0.645810   
1457      0.933333   0.000000       1.0          1.00  ...   0.688669   
1458      0.766667   1.000000       1.0          0.75  ...   0.414497   
1459      0.250000   0.666667       1.0          1.00  ...   0.468559   

      BsmtFullBath  FullBath  KitchenQual  Fireplaces  GarageType  \
0         0.333333  0.666667     0.666667    0.000000    0.166667   
1         0.000000  0.666667     1.000000    0.333333    0.166667   
2         0.333333  0.666667     0.666667    0.333333    0.166667   
3         0.333333  0.333333     0.666667    0.333333    0.833333   
4         0.333333  0.666667     0.666667    0.333333    0.166667   
...            ...       ...          ...         ...         ...   
1455      0.000000  0.666667     1.000000    0.333333    0.166667   
1456      0.333333  0.666667     1.000000    0.666667    0.166667   
1457      0.000000  0.666667     0.666667    0.666667    0.166667   
1458      0.333333  0.333333     0.666667    0.000000    0.166667   
1459      0.333333  0.333333     1.000000    0.000000    0.166667   

      GarageFinish  GarageCars  PavedDrive  SaleCondition  
0         0.666667        0.50         1.0            0.8  
1         0.666667        0.50         1.0            0.8  
2         0.666667        0.50         1.0            0.8  
3         1.000000        0.75         1.0            0.0  
4         0.666667        0.75         1.0            0.8  
...            ...         ...         ...            ...  
1455      0.666667        0.50         1.0            0.8  
1456      1.000000        0.50         1.0            0.8  
1457      0.666667        0.25         1.0            0.8  
1458      1.000000        0.25         1.0            0.8  
1459      0.000000        0.25         1.0            0.8  

[1460 rows x 24 columns]

In [4]:
Y_train=X_train['SalePrice']

In [5]:
Y_train

0       12.247694
1       12.109011
2       12.317167
3       11.849398
4       12.429216
          ...    
1455    12.072541
1456    12.254863
1457    12.493130
1458    11.864462
1459    11.901583
Name: SalePrice, Length: 1460, dtype: float64

In [6]:
Y_train.shape

(1460,)

In [7]:
Y_train=Y_train.values.reshape(-1,1)

In [8]:
Y_train.shape

(1460, 1)

In [9]:
from sklearn.preprocessing import MinMaxScaler
Scaler=MinMaxScaler()
y_train=Scaler.fit_transform(Y_train)

In [10]:
y_train

array([[0.58143069],
       [0.53631912],
       [0.60402899],
       ...,
       [0.66126699],
       [0.45677119],
       [0.46884616]])

In [11]:
X_train=X_train.drop(['Id','SalePrice'], axis=1)

In [12]:
X_train.head()

LotShape  BldgType  OverallQual  YearBuilt  YearRemodAdd  ExterQual  \
0       1.0       0.0     0.666667   0.949275      0.883333   0.666667   
1       1.0       0.0     0.555556   0.753623      0.433333   1.000000   
2       0.0       0.0     0.666667   0.934783      0.866667   0.666667   
3       0.0       0.0     0.666667   0.311594      0.333333   1.000000   
4       0.0       0.0     0.777778   0.927536      0.833333   0.666667   

   BsmtQual  BsmtExposure  BsmtFinType1  HeatingQC  ...  GrLivArea  \
0       0.5          1.00      0.333333        0.0  ...   0.577712   
1       0.5          0.25      0.000000        0.0  ...   0.470245   
2       0.5          0.75      0.333333        0.0  ...   0.593095   
3       1.0          1.00      0.000000        0.5  ...   0.579157   
4       0.5          0.00      0.333333        0.0  ...   0.666523   

   BsmtFullBath  FullBath  KitchenQual  Fireplaces  GarageType  GarageFinish  \
0      0.333333  0.666667     0.666667    0.000000    0.166667      0.666667   
1      0.000000  0.666667     1.000000    0.333333    0.166667      0.666667   
2      0.333333  0.666667     0.666667    0.333333    0.166667      0.666667   
3      0.333333  0.333333     0.666667    0.333333    0.833333      1.000000   
4      0.333333  0.666667     0.666667    0.333333    0.166667      0.666667   

   GarageCars  PavedDrive  SaleCondition  
0        0.50         1.0            0.8  
1        0.50         1.0            0.8  
2        0.50         1.0            0.8  
3        0.75         1.0            0.0  
4        0.75         1.0            0.8  

[5 rows x 22 columns]

In [13]:
X_test=pd.read_csv('Final_X_Test.csv')

In [14]:
X_test

Id  LotShape  BldgType  OverallQual  YearBuilt  YearRemodAdd  \
0     1461       1.0      0.00     0.444444   0.625954      0.183333   
1     1462       0.0      0.00     0.555556   0.603053      0.133333   
2     1463       0.0      0.00     0.444444   0.900763      0.800000   
3     1464       0.0      0.00     0.555556   0.908397      0.800000   
4     1465       0.0      1.00     0.777778   0.862595      0.700000   
...    ...       ...       ...          ...        ...           ...   
1454  2915       1.0      0.75     0.333333   0.694656      0.333333   
1455  2916       1.0      1.00     0.333333   0.694656      0.333333   
1456  2917       1.0      0.00     0.444444   0.618321      0.766667   
1457  2918       1.0      0.00     0.444444   0.862595      0.700000   
1458  2919       1.0      0.00     0.666667   0.870229      0.733333   

      ExterQual  BsmtQual  BsmtExposure  BsmtFinType1  ...  GrLivArea  \
0      1.000000       1.0           1.0      0.833333  ...   0.312253   
1      1.000000       1.0           1.0      0.000000  ...   0.468253   
2      1.000000       0.5           1.0      0.333333  ...   0.548792   
3      1.000000       1.0           1.0      0.333333  ...   0.542672   
4      0.666667       0.5           1.0      0.000000  ...   0.453388   
...         ...       ...           ...           ...  ...        ...   
1454   1.000000       1.0           1.0      1.000000  ...   0.390532   
1455   1.000000       1.0           1.0      0.833333  ...   0.390532   
1456   1.000000       1.0           1.0      0.000000  ...   0.435686   
1457   1.000000       0.5           0.0      0.333333  ...   0.343654   
1458   1.000000       0.5           0.0      0.500000  ...   0.629981   

      BsmtFullBath  FullBath  KitchenQual  Fireplaces  GarageType  \
0         0.000000      0.25          1.0        0.00    0.166667   
1         0.000000      0.25          0.5        0.00    0.166667   
2         0.000000      0.50          1.0        0.25    0.166667   
3         0.000000      0.50          0.5        0.25    0.166667   
4         0.000000      0.50          0.5        0.00    0.166667   
...            ...       ...          ...         ...         ...   
1454      0.000000      0.25          1.0        0.00    1.000000   
1455      0.000000      0.25          1.0        0.00    0.666667   
1456      0.333333      0.25          1.0        0.25    0.833333   
1457      0.000000      0.25          1.0        0.00    1.000000   
1458      0.000000      0.50          1.0        0.25    0.166667   

      GarageFinish  GarageCars  PavedDrive  SaleCondition  
0         1.000000         0.2         1.0            0.8  
1         1.000000         0.2         1.0            0.8  
2         0.000000         0.4         1.0            0.8  
3         0.000000         0.4         1.0            0.8  
4         0.666667         0.4         1.0            0.8  
...            ...         ...         ...            ...  
1454      0.333333         0.0         1.0            0.8  
1455      1.000000         0.2         1.0            0.0  
1456      1.000000         0.4         1.0            0.0  
1457      0.333333         0.0         1.0            0.8  
1458      0.000000         0.6         1.0            0.8  

[1459 rows x 23 columns]

In [15]:
X_test=X_test.drop('Id', axis=1)

In [16]:
X_test.head()

LotShape  BldgType  OverallQual  YearBuilt  YearRemodAdd  ExterQual  \
0       1.0       0.0     0.444444   0.625954      0.183333   1.000000   
1       0.0       0.0     0.555556   0.603053      0.133333   1.000000   
2       0.0       0.0     0.444444   0.900763      0.800000   1.000000   
3       0.0       0.0     0.555556   0.908397      0.800000   1.000000   
4       0.0       1.0     0.777778   0.862595      0.700000   0.666667   

   BsmtQual  BsmtExposure  BsmtFinType1  HeatingQC  ...  GrLivArea  \
0       1.0           1.0      0.833333        1.0  ...   0.312253   
1       1.0           1.0      0.000000        1.0  ...   0.468253   
2       0.5           1.0      0.333333        0.5  ...   0.548792   
3       1.0           1.0      0.333333        0.0  ...   0.542672   
4       0.5           1.0      0.000000        0.0  ...   0.453388   

   BsmtFullBath  FullBath  KitchenQual  Fireplaces  GarageType  GarageFinish  \
0           0.0      0.25          1.0        0.00    0.166667      1.000000   
1           0.0      0.25          0.5        0.00    0.166667      1.000000   
2           0.0      0.50          1.0        0.25    0.166667      0.000000   
3           0.0      0.50          0.5        0.25    0.166667      0.000000   
4           0.0      0.50          0.5        0.00    0.166667      0.666667   

   GarageCars  PavedDrive  SaleCondition  
0         0.2         1.0            0.8  
1         0.2         1.0            0.8  
2         0.4         1.0            0.8  
3         0.4         1.0            0.8  
4         0.4         1.0            0.8  

[5 rows x 22 columns]

#Linear Regression

In [17]:
from sklearn.linear_model import LinearRegression
LRmodel=LinearRegression()

In [18]:
LRmodel.fit(X_train,Y_train)

LinearRegression()

In [19]:
Y_LR_predict=LRmodel.predict(X_test)

In [20]:
Y_LR_predict

array([[11.47843217],
       [11.88757475],
       [11.99050138],
       ...,
       [11.79181297],
       [11.60981295],
       [12.28166769]])

In [21]:
Y_train_predict_LR=LRmodel.predict(X_train)

In [22]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [23]:
r2_LR=r2_score(Y_train,Y_train_predict_LR)
print("r2",r2_LR)

r2 0.8728097997510209


In [24]:
MAE_LR=mean_absolute_error(Y_train,Y_train_predict_LR)
print("Mae",MAE_LR)

Mae 0.10044044433433046


In [25]:
MSE_LR=mean_squared_error(Y_train,Y_train_predict_LR)
print("Mae",MSE_LR)

Mae 0.020280796188260834


In [26]:
RMSE_LR=np.sqrt(MSE_LR)
print("RMSE",RMSE_LR)

RMSE 0.14241066037435834


#Random Forest Regression

In [27]:
from sklearn.ensemble import RandomForestRegressor
RFR_model= RandomForestRegressor(n_estimators=10, random_state=0)

In [28]:
RFR_model.fit(X_train,Y_train)

C:\Users\bharg\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(n_estimators=10, random_state=0)

In [29]:
Y_predict=RFR_model.predict(X_test)

In [30]:
Y_predict

array([11.66759888, 11.81789534, 12.04227092, ..., 11.89184936,
       11.58347845, 12.27883417])

In [31]:
Y_train_predict=RFR_model.predict(X_train)

In [32]:
r2_RFR=r2_score(Y_train,Y_train_predict)
print("r2",r2_RFR)

r2 0.9731720218444516


In [33]:
MAE_RFR=mean_absolute_error(Y_train,Y_train_predict)
print("Mae",MAE_RFR)

Mae 0.04307484072505915


In [34]:
MSE_RFR=mean_squared_error(Y_train,Y_train_predict)
print("Mae",MSE_RFR)

Mae 0.004277788352016984


In [35]:
RMSE_RFR=np.sqrt(MSE_RFR)
print("RMSE",RMSE_RFR)

RMSE 0.06540480373808169


#Decision Tree

In [36]:
from sklearn.tree import DecisionTreeRegressor
DT_model=DecisionTreeRegressor(random_state=0)

In [37]:
DT_model.fit(X_train,Y_train)

DecisionTreeRegressor(random_state=0)

In [38]:
Y_DT_Predict=DT_model.predict(X_test)

In [39]:
Y_DT_Predict

array([11.57590026, 11.71993963, 12.28995413, ..., 11.8493977 ,
       11.68266824, 12.27792808])

In [40]:
Y_train_predict_DT=DT_model.predict(X_train)

In [41]:
r2_DT=r2_score(Y_train,Y_train_predict_DT)
print("r2",r2_DT)

r2 0.9999784909387734


In [42]:
Mae_DT=mean_absolute_error(Y_train,Y_train_predict_DT)
print("Mae",Mae_DT)

Mae 0.0001234374822740769


In [43]:
MSE_DT=mean_squared_error(Y_train,Y_train_predict_DT)
print("Mae",MSE_DT)

Mae 3.4296737176514427e-06
